export const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mark = '<a class="wordmark" href="/"><img src="/brand/fambit-mark.png" alt="" width="38" height="38"/><span>FAMBIT</span></a>';
function document(title, content, script = '') {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} · FAMBIT</title><meta name="description" content="Biblioteca de familias para usar desde Revit."><link rel="icon" href="/brand/fambit-mark.png"><link rel="stylesheet" href="/portal.css"></head><body>${content}${script}</body></html>`;
}
export function loginPage(hasTotp, failed = false) {
  return document('Administración', `<main class="login-layout"><section class="login-card">${mark}<p class="eyebrow">ADMINISTRACIÓN</p><h1>Tu biblioteca,<br>en tus manos.</h1><p class="muted">Accede para gestionar tus familias y las licencias de tus clientes.</p><form id="login-form" method="post" action="/admin/login"><label for="user">Usuario</label><input id="user" name="user" autocomplete="username" maxlength="100" required autofocus><label for="password">Contraseña</label><input id="password" name="password" type="password" autocomplete="current-password" minlength="20" maxlength="1024" required>${hasTotp ? '<label for="code">Código de tu autenticador</label><input id="code" name="code" autocomplete="one-time-code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="000000" required><p class="hint">Introduce el código de seis dígitos de tu aplicación de autenticación.</p>' : ''}<p id="login-error" class="error" role="alert">${failed ? 'No se pudo iniciar sesión. Revisa tus datos o espera al siguiente código.' : ''}</p><button class="button" type="submit">Entrar al panel</button></form><a class="back-link" href="/">Volver a FAMBIT</a></section></main>`, '<script src="/login.js" defer></script>');
}
export function publicPage({downloadUrl = '', downloadVersion = '', downloadRevit = '', contactEmail = ''}) {
  const download = downloadUrl ? `<a class="button" href="${escapeHtml(downloadUrl)}" rel="noopener noreferrer">Descargar FAMBIT <span aria-hidden="true">↓</span></a><p class="hint">Versión ${escapeHtml(downloadVersion)} · Revit ${escapeHtml(downloadRevit)} · Windows</p>` : '<span class="coming-soon">Lanzamiento en preparación</span><p class="hint">El instalador estará disponible aquí cuando finalicen las pruebas de esta versión.</p>';
  const contact = contactEmail ? `<a class="button secondary" href="mailto:${escapeHtml(contactEmail)}?subject=Licencia%20FAMBIT">Consultar una licencia</a>` : '';
  return document('Familias para Revit', `<header class="site-header">${mark}<nav aria-label="Principal"><a href="#como-funciona">Cómo funciona</a><a href="#descargar">Descargar</a><a class="admin-link" href="/admin">Administración</a></nav></header><main><section class="hero"><div class="hero-copy"><p class="eyebrow">TU BIBLIOTECA BIM</p><h1>La familia que buscas.<br>Dentro de Revit.</h1><p class="lead">Explora componentes por categoría, consulta sus vistas previas y llévalos a tu proyecto desde un panel integrado.</p><div class="hero-actions"><a class="button" href="#descargar">Conocer FAMBIT <span aria-hidden="true">↗</span></a>${contact}</div><p class="quiet">Arquitectura · Estructuras · Instalaciones</p></div><div class="brand-panel"><img src="/brand/fambit-mark.png" alt="Símbolo modular tridimensional de FAMBIT" width="250" height="250"><p>Familias conectadas.<br>Proyectos en movimiento.</p></div></section><section id="como-funciona" class="steps"><div class="section-heading"><p class="eyebrow">DE LA BIBLIOTECA AL PROYECTO</p><h2>Un espacio para tus componentes.</h2></div><div class="steps-grid"><article><span class="step-number">01</span><h3>Instala y activa</h3><p>Instala el complemento para tu versión de Revit e introduce el correo y la licencia que recibiste.</p></article><article><span class="step-number">02</span><h3>Encuentra tu familia</h3><p>Busca por nombre o explora categorías y subcategorías. Consulta la imagen y la versión de cada familia.</p></article><article><span class="step-number">03</span><h3>Llévala al proyecto</h3><p>Carga la familia y colócala en una vista compatible. Los elementos que requieren un anfitrión siguen las indicaciones de Revit.</p></article></div></section><section id="descargar" class="download-section"><div><p class="eyebrow">EMPIEZA CON FAMBIT</p><h2>Tu próximo componente<br>empieza aquí.</h2><p class="muted">Necesitas Revit compatible y conexión a internet para acceder a la biblioteca. La licencia de FAMBIT se adquiere por separado.</p></div><div class="download-actions">${download}${contact}</div></section></main><footer><span>FAMBIT · Biblioteca de familias</span><span>Revit es un producto de Autodesk.</span></footer>`);
}
