'use client';
import {useEffect,useMemo,useState,useCallback,type FormEvent} from 'react';
import {Box,Building2,Armchair,DoorOpen,Columns3,Bath,Lamp,Library,KeyRound,CloudUpload,Package,Search,Plus,ArrowUpRight,ArrowLeft,RefreshCw,Monitor,Check,Copy,FileBox,FolderOpen,ShieldCheck,LoaderCircle,Download,Eye,EyeOff,SlidersHorizontal,Grid2X2} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import {categories,type Family,type License,type Device,type Release} from '@/lib/catalog';
const icons={Building2,Armchair,DoorOpen,Columns3,Bath,Lamp,Box};
const fmt=(t:number)=>new Date(t*1000).toLocaleDateString('es-PE',{day:'2-digit',month:'short',year:'numeric'});
const bytes=(n:number)=>n>=1048576?(n/1048576).toFixed(1)+' MB':Math.round(n/1024)+' KB';
async function api(path:string,options:RequestInit={}){
 const read=async(address:string)=>{const response=await fetch('/api'+address,options);const data:any=await response.json().catch(()=>({error:'No se pudo conectar con el repositorio.'}));if(!response.ok){if(response.status===401&&data.code==='ADMIN_SESSION_REQUIRED')window.location.assign('/admin/login');throw new Error(data.error||'No se pudo completar la operación.');}return data;};
 const result=await read(path);if((options.method??'GET')!=='GET'||!['/families','/licenses'].includes(path))return result;
 const field=path==='/families'?'families':'licenses',seen=new Set<string>();let cursor=result.nextCursor;
 while(cursor){if(seen.has(cursor)||seen.size>=100)throw new Error('La biblioteca supera el límite de esta vista. Contacta al administrador.');seen.add(cursor);const page=await read(path+'?cursor='+encodeURIComponent(cursor));result[field].push(...page[field]);if(result.devices)result.devices.push(...page.devices);cursor=page.nextCursor;}
 return result;
}
const write=(path:string,data:unknown,method='POST')=>api(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function Choice({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>;}
const versionItems=[{value:'all',label:'Todas las versiones'},...[2024,2025,2026,2027].map(y=>({value:String(y),label:'Revit '+y}))];
export default function Workspace({name,email,logoutAction,usage,onRefreshUsage}:{name:string;email:string;logoutAction?:string;usage?:{downloadBytes:number;dailyLimitBytes:number;storedBytes:number;storageLimitBytes:number};onRefreshUsage?:()=>void}){
 const [tab,setTab]=useState('library'),[families,setFamilies]=useState<Family[]>([]),[licenses,setLicenses]=useState<License[]>([]),[devices,setDevices]=useState<Device[]>([]),[releases,setReleases]=useState<Release[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[subcategory,setSubcategory]=useState('all'),[version,setVersion]=useState('all');
 const [modal,setModal]=useState<'family'|'license'|'release'|'key'|null>(null),[editFamily,setEditFamily]=useState<Family|null>(null),[detail,setDetail]=useState<Family|null>(null),[editLicense,setEditLicense]=useState<License|null>(null),[licenseKey,setLicenseKey]=useState('');
 const [busy,setBusy]=useState(false),[formCategory,setFormCategory]=useState('arquitectura'),[formSubcategory,setFormSubcategory]=useState('otros'),[formVersion,setFormVersion]=useState('2024');
 const refresh=useCallback(async()=>{setError('');try{const [f,l,r]=await Promise.all([api('/families'),api('/licenses'),api('/releases')]);setFamilies(f.families);setLicenses(l.licenses);setDevices(l.devices);setReleases(r.releases);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();},[refresh]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();Promise.resolve(ctx.registerTool({name:'search_revit_library',title:'Buscar familias Revit',description:'Filtra la biblioteca visible por nombre. No modifica archivos ni licencias.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input?.query!=='string'||input.query.length>200)throw new Error('Consulta inválida');setTab('library');chooseCategory('all');setSearch(input.query);return {families:families.filter(f=>f.name.toLowerCase().includes(input.query.toLowerCase())).map(f=>({id:f.id,name:f.name,revit:f.revit}))};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[families]);
 const visible=useMemo(()=>families.filter(f=>(category==='all'||f.category===category)&&(subcategory==='all'||f.subcategory===subcategory)&&(version==='all'||f.revit<=Number(version))&&(f.name+' '+f.description).toLowerCase().includes(search.toLowerCase())),[families,category,subcategory,version,search]);
 const shownLicenses=licenses.filter(l=>(l.name+' '+l.email).toLowerCase().includes(search.toLowerCase()));
 const currentCategory=categories.find(c=>c.id===category);
 const active=licenses.filter(l=>l.status==='active'&&l.expires>Date.now()/1000).length;
 async function run(action:()=>Promise<void>){setBusy(true);try{await action();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 function openFamily(f:Family|null=null){setEditFamily(f);setFormCategory(f?.category??(category==='all'?'arquitectura':category));setFormSubcategory(f?.subcategory??(subcategory==='all'?'otros':subcategory));setFormVersion(String(f?.revit??2024));setModal('family');}
 async function submitFamily(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);data.set('category',formCategory);data.set('subcategory',formSubcategory);data.set('revit',formVersion);if(editFamily)data.set('id',editFamily.id);await run(async()=>{await api('/families',{method:'POST',body:data});setModal(null);await refresh();toast.success(editFamily?'Familia actualizada.':'Familia publicada.');});}
 async function submitLicense(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{const result=await write('/licenses',{name:f.get('name'),email:f.get('email'),maxDevices:Number(f.get('maxDevices')),expires:Math.floor(new Date(String(f.get('expires'))+'T23:59:59Z').getTime()/1000)});setLicenseKey(result.key);setModal('key');await refresh();});}
 async function updateLicense(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{await write('/licenses/'+editLicense!.id,{expires:Math.floor(new Date(String(f.get('expires'))+'T23:59:59Z').getTime()/1000),maxDevices:Number(f.get('maxDevices'))},'PATCH');setEditLicense(null);await refresh();toast.success('Licencia actualizada.');});}
 async function submitRelease(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{await write('/releases',Object.fromEntries(f));setModal(null);await refresh();toast.success('Versión registrada.');});}
 const chooseCategory=(id:string)=>{setCategory(id);setSubcategory('all');};
 const go=(value:string)=>{setTab(value);setSearch('');};
 return <SidebarProvider style={{'--sidebar-width':'224px'} as React.CSSProperties}><Sidebar className="border-r border-[#e8ebef]"><SidebarHeader className="brand"><div className="brand-icon"><img src="/brand/fambit-mark.png" alt="" width="38" height="38"/></div><div><strong>FAMBIT</strong><small>Familias para Revit</small></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Espacio de trabajo</SidebarGroupLabel><SidebarMenu>{[{id:'library',name:'Biblioteca',icon:Library},{id:'licenses',name:'Cuentas y licencias',icon:KeyRound},{id:'releases',name:'Add-in y versiones',icon:Package}].map(item=><SidebarMenuItem key={item.id}><SidebarMenuButton size="lg" isActive={tab===item.id} onClick={()=>go(item.id)}><item.icon/><span>{item.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><SidebarGroup className="mt-5"><SidebarGroupLabel>Categorías</SidebarGroupLabel><SidebarMenu>{categories.map(c=>{const Icon=icons[c.icon];return <SidebarMenuItem key={c.id}><SidebarMenuButton onClick={()=>{go('library');chooseCategory(c.id);}} isActive={tab==='library'&&category===c.id}><Icon/><span>{c.name}</span><span className="ml-auto text-[#98a3b0]">{families.filter(f=>f.category===c.id).length}</span></SidebarMenuButton></SidebarMenuItem>;})}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter>{usage&&<div className="usage-note"><strong>Consumo de la biblioteca</strong><span>Hoy: {bytes(usage.downloadBytes)} / {bytes(usage.dailyLimitBytes)}</span><span>Archivos: {bytes(usage.storedBytes)} / {bytes(usage.storageLimitBytes)}</span><button type="button" onClick={onRefreshUsage}>Actualizar consumo</button></div>}<div className="private-note"><ShieldCheck size={20}/><div><strong>Administración privada</strong><span>Tú controlas el acceso.</span></div></div><div className="profile"><span className="avatar">{name.slice(0,1).toUpperCase()}</span><div><strong>Mi espacio</strong><span title={email}>{email}</span></div></div>{logoutAction&&<form method="post" action={logoutAction}><Button type="submit" variant="ghost" className="w-full text-sm">Cerrar sesión</Button></form>}</SidebarFooter></Sidebar>
 <SidebarInset><header className="topbar"><div className="crumb"><SidebarTrigger/><span>Mi espacio</span><span>/</span><strong>{tab==='library'?'Biblioteca':tab==='licenses'?'Cuentas y licencias':'Add-in y versiones'}</strong></div><span className="version-pill"><Box size={15}/> Biblioteca Revit</span></header><main className={"workspace theme-"+(currentCategory?.color??"lavender")}>
 <div className="page-heading"><div><div className="eyebrow">FAMBIT / {tab==='library'?'REPOSITORIO':tab==='licenses'?'ACCESOS':'DISTRIBUCIÓN'}</div><h1>{tab==='library'?'Biblioteca de familias':tab==='licenses'?'Cuentas y licencias':'Un instalador. Tu biblioteca.'}</h1><p>{tab==='library'?'Organiza tus componentes y mantén cada proyecto al día.':tab==='licenses'?'Decide quién accede, hasta cuándo y desde cuántos equipos.':'Administra las versiones que recibirán tus usuarios.'}</p></div><Button className="primary-action" onClick={()=>tab==='library'?openFamily():setModal(tab==='licenses'?'license':'release')}><Plus size={18}/>{tab==='library'?'Subir familia':tab==='licenses'?'Crear cuenta':'Registrar versión'}</Button></div>
 {error&&<div className="error-banner" role="alert"><span>{error}</span><Button variant="outline" onClick={()=>void refresh()}>Reintentar</Button></div>}
 {tab==='library'&&<><div className="collection-summary"><div><span className="summary-icon lavender"><Library size={21}/></span><span><strong>{families.length}</strong> familias en tu biblioteca</span></div><div><span className="summary-icon mint"><Check size={20}/></span><span><strong>{families.filter(f=>f.published).length}</strong> publicadas</span></div><div className="summary-last"><CloudUpload size={18}/><span>Actualización centralizada</span></div></div><div className="section-label"><h2>Explorar por categoría</h2><button className="text-button" onClick={()=>{chooseCategory('all');setSearch('');setVersion('all');}}>Ver todas <ArrowUpRight size={16}/></button></div><div className="category-grid">{categories.map(c=>{const Icon=icons[c.icon];return <button className={'category-card '+c.color+(category===c.id?' selected':'')} key={c.id} onClick={()=>chooseCategory(category===c.id?'all':c.id)} aria-pressed={category===c.id}><div className="category-top"><Icon size={29} strokeWidth={1.35}/><span>{families.filter(f=>f.category===c.id).length.toString().padStart(2,'0')}</span></div><h3>{c.name}</h3><p>{c.detail}</p></button>;})}</div>{currentCategory&&<div className="subcategory-bar" aria-label="Subcategorías"><button className={subcategory==='all'?'active':''} onClick={()=>setSubcategory('all')}>Todo en {currentCategory.name}</button>{currentCategory.subcategories.map(sub=><button key={sub.id} className={subcategory===sub.id?'active':''} onClick={()=>setSubcategory(sub.id)}>{sub.name}<span>{families.filter(f=>f.category===currentCategory.id&&f.subcategory===sub.id).length}</span></button>)}</div>}<div className="list-toolbar"><h2>{currentCategory?.name??'Todas las familias'} <span>{visible.length}</span></h2><div className="filters"><div className="search-field"><Search size={17}/><Input aria-label="Buscar familias" placeholder="Buscar una familia…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Choice label="Versión de Revit" value={version} onChange={setVersion} items={versionItems}/></div></div>
 {loading?<div className="family-grid">{[1,2,3].map(i=><Skeleton key={i} className="h-52 rounded-xl"/>)}</div>:visible.length?<div className="family-grid">{visible.map(f=>{const c=categories.find(c=>c.id===f.category)!;const Icon=icons[c?.icon??'Box'];return <article className="family-card" key={f.id}><button className={'family-preview '+(c?.color??'lavender')} onClick={()=>setDetail(f)} aria-label={'Ver '+f.name}>{f.hasThumbnail?<img src={'/api/families/'+f.id+'/thumbnail?updated='+f.updated} alt={f.name}/>:<Icon size={51} strokeWidth={1.2}/>}<span className={'state-badge '+(f.published?'':'hidden-badge')}>{f.published?'Publicada':'Oculta'}</span></button><div className="family-body"><button onClick={()=>setDetail(f)} className="family-name" title={f.name}>{f.name}</button><span className="family-category">{c?.name} · {c?.subcategories.find(sub=>sub.id===f.subcategory)?.name??'Otros elementos'}</span><div className="family-meta"><span>Revit {f.revit}+</span><span>{bytes(f.size)}</span><span>v{f.revision}</span></div></div></article>;})}</div>:<div className="empty-state"><div className="empty-icon"><FolderOpen size={34} strokeWidth={1.4}/></div><h3>{families.length?'No hay coincidencias':'Tu primera familia empieza aquí'}</h3><p>{families.length?'Prueba otro nombre, categoría o versión de Revit.':'Sube un archivo .rfa, añade una miniatura y elige su categoría.'}</p><Button variant="outline" onClick={()=>families.length?(setSearch(''),chooseCategory('all'),setVersion('all')):openFamily()}>{families.length?'Limpiar filtros':'Subir mi primera familia'}<ArrowUpRight size={16}/></Button></div>}<div className="bottom-note"><FileBox size={17}/><span>La versión indica el Revit mínimo declarado al publicar. La carga definitiva se valida dentro de Revit.</span></div></>}
 {tab==='licenses'&&<><div className="stat-grid"><div className="stat-card lavender"><KeyRound/><span>Cuentas registradas</span><strong>{licenses.length}</strong></div><div className="stat-card mint"><ShieldCheck/><span>Licencias activas</span><strong>{active}</strong></div><div className="stat-card blue"><Monitor/><span>Equipos vinculados</span><strong>{devices.length}</strong></div></div><div className="list-toolbar"><h2>Tus cuentas</h2><div className="search-field"><Search size={17}/><Input placeholder="Buscar nombre o correo…" aria-label="Buscar cuentas" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>{loading?<Skeleton className="h-60"/>:shownLicenses.length?<div className="table-surface"><Table><TableHeader><TableRow><TableHead>Cuenta</TableHead><TableHead>Estado</TableHead><TableHead>Vencimiento</TableHead><TableHead>Equipos</TableHead><TableHead>Licencia</TableHead><TableHead className="text-right">Administrar</TableHead></TableRow></TableHeader><TableBody>{shownLicenses.map(l=>{const status=l.status==='suspended'?'Suspendida':l.expires<Date.now()/1000?'Vencida':'Activa';return <TableRow key={l.id}><TableCell><strong>{l.name}</strong><small className="block text-muted-foreground">{l.email}</small></TableCell><TableCell><span className={'status-tag '+(status==='Activa'?'mint':'peach')}>{status}</span></TableCell><TableCell>{fmt(l.expires)}</TableCell><TableCell>{l.device_count} / {l.max_devices}</TableCell><TableCell className="font-mono">••• {l.key_suffix}</TableCell><TableCell className="text-right"><Button variant="ghost" onClick={()=>setEditLicense(l)}><SlidersHorizontal size={16}/>Gestionar</Button></TableCell></TableRow>;})}</TableBody></Table></div>:<div className="empty-state"><div className="empty-icon"><KeyRound size={32}/></div><h3>{licenses.length?'No hay coincidencias':'Tu biblioteca, con acceso controlado'}</h3><p>Crea una cuenta y entrega una clave de activación a su usuario.</p><Button variant="outline" onClick={()=>setModal('license')}><Plus size={16}/>Crear cuenta</Button></div>}<div className="bottom-note"><ShieldCheck size={17}/><span>Las claves completas se muestran una sola vez. Puedes generar una nueva desde la cuenta.</span></div></>}
 {tab==='releases'&&<><div className="release-intro"><div className="release-symbol"><img src="/brand/fambit-mark.png" alt="FAMBIT" width="76" height="76"/></div><div><span className="eyebrow">COMPLEMENTO PARA WINDOWS</span><h2>FAMBIT para Revit</h2><p>Panel acoplable, familias con imagen y colocación directa en tu proyecto.</p><span className="status-tag peach">Versión en preparación 0.5.0</span></div></div><div className="compatibility"><h2>Compatibilidad prevista</h2><div>{[{y:'2024',runtime:'.NET Framework 4.8'},{y:'2025 / 2026',runtime:'.NET 8 · revisar actualizaciones a .NET 10'},{y:'2027',runtime:'.NET 10'}].map(v=><div key={v.y}><strong>Revit {v.y}</strong><span>{v.runtime}</span></div>)}</div><p>Las versiones futuras requieren adaptar y probar el complemento. Los archivos no se convierten a una versión anterior.</p></div><div className="section-label"><h2>Versiones del instalador</h2></div>{releases.length?<div className="release-list">{releases.map(r=><article key={r.id}><div className="summary-icon lavender"><Package size={22}/></div><div><h3>Versión {r.version}</h3><span>{fmt(r.created)}</span><p>{r.notes}</p></div><a className="download-link" href={r.url} target="_blank" rel="noreferrer">Descargar <Download size={16}/></a></article>)}</div>:<div className="empty-state"><h3>Aún no hay un instalador publicado</h3><p>Registra el enlace del instalador después de compilarlo y probarlo en Windows con Revit.</p><Button variant="outline" onClick={()=>setModal('release')}>Registrar versión<Plus size={16}/></Button></div>}</>}
 </main><footer className="app-footer"><span>FAMBIT</span><span>Biblioteca · Control · Versiones</span></footer></SidebarInset>
 <Dialog open={modal!==null} onOpenChange={open=>{if(!open&&!busy)setModal(null);}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-[540px]"><DialogHeader><DialogTitle>{modal==='family'?(editFamily?'Actualizar familia':'Subir una familia'):modal==='license'?'Crear cuenta y licencia':modal==='release'?'Registrar versión del instalador':'Tu clave de activación'}</DialogTitle><DialogDescription>{modal==='family'?'Publica un archivo RFA y su información en la biblioteca.':modal==='license'?'El usuario activará el add-in con su correo y esta licencia.':modal==='release'?'Añade una versión ya compilada, firmada y probada.':'Copia esta clave antes de cerrar. Después solo podrás generar una nueva.'}</DialogDescription></DialogHeader>
 {modal==='family'&&<form className="form-grid" onSubmit={submitFamily}><Label>Nombre<Input name="name" defaultValue={editFamily?.name} maxLength={200} placeholder="Ej. Silla de oficina" required/></Label><div className="form-row"><Label>Categoría<Choice label="Categoría" value={formCategory} onChange={id=>{setFormCategory(id);setFormSubcategory('otros');}} items={categories.map(c=>({value:c.id,label:c.name}))}/></Label><Label>Versión original<Choice label="Revit original" value={formVersion} onChange={setFormVersion} items={versionItems.slice(1)}/></Label></div><Label>Subcategoría<Choice label="Subcategoría" value={formSubcategory} onChange={setFormSubcategory} items={(categories.find(c=>c.id===formCategory)?.subcategories??[]).map(sub=>({value:sub.id,label:sub.name}))}/></Label><Label>Descripción<Textarea name="description" defaultValue={editFamily?.description} maxLength={1500} placeholder="Materiales, tipos y características…"/></Label><Label>{editFamily?'Reemplazar archivo RFA · opcional':'Archivo de familia · hasta 25 MB'}<Input name="file" type="file" accept=".rfa" required={!editFamily}/></Label><Label>Miniatura · PNG o JPG, hasta 2 MB<Input name="thumbnail" type="file" accept="image/png,image/jpeg"/></Label><p className="form-note">Puedes actualizar la imagen y la clasificación sin reemplazar el archivo. La familia debe estar guardada en la versión que indicas. El servidor revisa el formato básico; Revit valida su contenido.</p><Button disabled={busy} type="submit">{busy?<LoaderCircle className="animate-spin"/>:<CloudUpload size={17}/>} {busy?'Publicación en curso…':editFamily?'Publicar actualización':'Publicar familia'}</Button></form>}
 {modal==='license'&&<form className="form-grid" onSubmit={submitLicense}><Label>Nombre<Input name="name" required maxLength={200} placeholder="Nombre del usuario o estudio"/></Label><Label>Correo<Input name="email" type="email" required maxLength={254} placeholder="usuario@estudio.com"/></Label><div className="form-row"><Label>Válida hasta<Input name="expires" type="date" required min={new Date().toISOString().slice(0,10)} defaultValue={new Date(Date.now()+30*86400000).toISOString().slice(0,10)}/></Label><Label>Equipos permitidos<Input name="maxDevices" type="number" min={1} max={100} defaultValue={1} required/></Label></div><Button disabled={busy}>{busy?'Creación en curso…':'Crear cuenta y generar clave'}</Button></form>}
 {modal==='release'&&<form className="form-grid" onSubmit={submitRelease}><Label>Versión<Input name="version" placeholder="1.0.0" pattern="[0-9]+\.[0-9]+\.[0-9]+" required/></Label><Label>Enlace HTTPS del instalador<Input name="url" type="url" placeholder="https://…/FAMBIT-Setup.exe" required/></Label><Label>SHA-256 del instalador<Input name="sha256" minLength={64} maxLength={64} required placeholder="Huella del archivo compilado"/></Label><Label>Novedades<Textarea name="notes" required maxLength={2000}/></Label><Button disabled={busy}>{busy?'Registro en curso…':'Registrar versión'}</Button></form>}
 {modal==='key'&&<div className="form-grid"><code className="license-key">{licenseKey}</code><Button onClick={()=>void navigator.clipboard.writeText(licenseKey).then(()=>toast.success('Clave copiada.')).catch(()=>toast.error('Selecciona y copia la clave manualmente.'))}><Copy size={17}/>Copiar clave</Button><p className="form-note">La clave no se envía por correo automáticamente.</p></div>}
 </DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={o=>!o&&setDetail(null)}><DialogContent><DialogHeader><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>{detail&&categories.find(c=>c.id===detail.category)?.name}</DialogDescription></DialogHeader>{detail&&<div className="form-grid">{detail.hasThumbnail&&<img className="detail-image" src={'/api/families/'+detail.id+'/thumbnail'} alt={detail.name}/>}<p>{detail.description||'Sin descripción adicional.'}</p><div className="detail-specs"><span>Revit {detail.revit}+</span><span>{bytes(detail.size)}</span><span>Revisión {detail.revision}</span></div><p className="form-note">Actualizada el {fmt(detail.updated)}. Descarga administrativa; la carga en el proyecto se realiza desde el add-in.</p><Button asChild><a href={'/api/families/'+detail.id+'/file'}><Download size={17}/>Descargar RFA</a></Button><div className="form-row"><Button variant="outline" onClick={()=>{openFamily(detail);setDetail(null);}}><RefreshCw size={16}/>Editar familia</Button><Button disabled={busy} variant="outline" onClick={()=>void run(async()=>{await write('/families/'+detail.id,{published:!detail.published},'PATCH');setDetail(null);await refresh();toast.success(detail.published?'Familia oculta.':'Familia publicada.');})}>{detail.published?<EyeOff size={16}/>:<Eye size={16}/>} {detail.published?'Ocultar':'Publicar'}</Button></div></div>}</DialogContent></Dialog>
 <Dialog open={!!editLicense} onOpenChange={o=>!o&&!busy&&setEditLicense(null)}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{editLicense?.name}</DialogTitle><DialogDescription>{editLicense?.email}</DialogDescription></DialogHeader>{editLicense&&<><form className="form-grid" onSubmit={updateLicense}><div className="form-row"><Label>Vencimiento<Input type="date" name="expires" defaultValue={new Date(editLicense.expires*1000).toISOString().slice(0,10)} required/></Label><Label>Equipos permitidos<Input type="number" name="maxDevices" min={1} max={100} defaultValue={editLicense.max_devices} required/></Label></div><Button disabled={busy}>Guardar cambios</Button></form><div className="device-list"><h3>Equipos vinculados</h3>{devices.filter(d=>d.license_id===editLicense.id).map(d=><div key={d.id}><Monitor size={18}/><div><strong>{d.name}</strong><small>{fmt(d.last_seen)}</small></div><Button disabled={busy} variant="ghost" onClick={()=>void run(async()=>{await api('/devices/'+d.id+'?licenseId='+encodeURIComponent(d.license_id),{method:'DELETE'});await refresh();toast.success('Equipo liberado.');})}>Liberar</Button></div>)}{!devices.some(d=>d.license_id===editLicense.id)&&<p className="form-note">Aún no se ha activado en un equipo.</p>}</div><div className="form-row"><Button disabled={busy} variant="outline" onClick={()=>void run(async()=>{await write('/licenses/'+editLicense.id,{status:editLicense.status==='active'?'suspended':'active'},'PATCH');setEditLicense(null);await refresh();toast.success('Estado actualizado.');})}>{editLicense.status==='active'?'Suspender acceso':'Reactivar acceso'}</Button><Button disabled={busy} variant="outline" onClick={()=>void run(async()=>{const r=await write('/licenses/'+editLicense.id,{rotateKey:true},'PATCH');setLicenseKey(r.key);setEditLicense(null);setModal('key');await refresh();})}>Generar nueva clave</Button></div><p className="form-note">Una nueva clave desvincula los equipos anteriores. La suspensión bloquea las próximas solicitudes al servidor.</p></>}</DialogContent></Dialog>
 <Toaster position="bottom-right" richColors closeButton/></SidebarProvider>;
}
